##
import numpy as np
import matplotlib.pyplot as plt

##

data = np.genfromtxt("combined.dat")

##

plt.figure()
plt.plot(data[:, 0], data[:, 3], color="k", label="Total")
plt.plot(data[:, 0], data[:, 1], color="tab:red", ls="--", label="Electronic")
plt.plot(data[:, 0], data[:, 2], color="tab:blue", ls="--", label="Nuclear")
plt.xlabel(r"Depth [$\mu$m]", fontsize=16)
plt.ylabel("Energy loss [keV/nm]", fontsize=16)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.xlim(0, np.max(data[:, 0]) * 1.05)
plt.ylim(0, np.max(data[:, 3]) * 1.05)
plt.axvline(2, ls="--", color="tab:grey")
plt.legend(fontsize=14)
plt.tight_layout()
plt.savefig("layer_demo_GaN_SiC_maik.png")

plt.figure()
plt.plot(data[:, 0], data[:, 3], color="k", label="Total")
plt.plot(data[:, 0], data[:, 1], color="tab:red", ls="--", label="Electronic")
plt.plot(data[:, 0], data[:, 2], color="tab:blue", ls="--", label="Nuclear")
plt.annotate("GaN", (1, 20), ha="center", fontsize=18)
plt.annotate("SiC", (5, 20), ha="center", fontsize=18)
plt.xlabel(r"Depth [$\mu$m]", fontsize=16)
plt.ylabel("Energy loss [keV/nm]", fontsize=16)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.xlim(0, 8)
plt.ylim(0, np.max(data[:, 3]) * 1.05)
plt.axvline(2, ls="--", color="tab:grey")
plt.legend(fontsize=14)
plt.tight_layout()
plt.savefig("layer_demo_GaN_SiC_maik_zoomed.png")
plt.show()

##

data = np.genfromtxt("GaN_AlN_SiC.dat")
plt.figure()
plt.plot(data[:, 0], data[:, 3], color="k", label="Total")
plt.plot(data[:, 0], data[:, 1], color="tab:red", ls="--", label="Electronic")
plt.plot(data[:, 0], data[:, 2], color="tab:blue", ls="--", label="Nuclear")
plt.xlabel(r"Depth [$\mu$m]", fontsize=20)
plt.ylabel("Energy loss [keV/nm]", fontsize=20)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.xlim(0, np.max(data[:, 0]) * 1.05)
plt.ylim(0, np.max(data[:, 3]) * 1.05)
plt.axvline(1, ls="--", color="tab:grey")
plt.axvline(2, ls="--", color="tab:grey")
plt.legend(fontsize=14)
plt.tight_layout()
plt.savefig("SRIM_GaN_AlN_SiC_maik.png")
plt.show()

plt.figure()
plt.plot(data[:, 0], data[:, 3], color="k", label="Total")
plt.plot(data[:, 0], data[:, 1], color="tab:red", ls="--", label="Electronic")
plt.plot(data[:, 0], data[:, 2], color="tab:blue", ls="--", label="Nuclear")
plt.annotate("GaN", (0.5, 20), ha="center", fontsize=20)
plt.annotate("AlN", (1.5, 20), ha="center", fontsize=20)
plt.annotate("SiC", (3, 20), ha="center", fontsize=20)
plt.xlabel(r"Depth [$\mu$m]", fontsize=16)
plt.ylabel("Energy loss [keV/nm]", fontsize=16)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.xlim(0, 5)
plt.ylim(0, np.max(data[:, 3]) * 1.05)
plt.axvline(1, ls="--", color="tab:grey")
plt.axvline(2, ls="--", color="tab:grey")
plt.legend(fontsize=14)
plt.tight_layout()
plt.savefig("SRIM_GaN_AlN_SiC_maik_zoomed.png")
plt.show()

##

data = np.genfromtxt("AlN_SiC.dat")
plt.figure()
plt.plot(data[:, 0], data[:, 3], color="k", label="Total")
plt.plot(data[:, 0], data[:, 1], color="tab:red", ls="--", label="Electronic")
plt.plot(data[:, 0], data[:, 2], color="tab:blue", ls="--", label="Nuclear")
plt.xlabel(r"Depth [$\mu$m]", fontsize=20)
plt.ylabel("Energy loss [keV/nm]", fontsize=20)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.xlim(0, np.max(data[:, 0]) * 1.05)
plt.ylim(0, np.max(data[:, 3]) * 1.05)
plt.axvline(2, ls="--", color="tab:grey")
plt.legend(fontsize=14)
plt.tight_layout()
plt.savefig("SRIM_AlN_SiC_maik.png")
plt.show()

plt.figure()
plt.plot(data[:, 0], data[:, 3], color="k", label="Total")
plt.plot(data[:, 0], data[:, 1], color="tab:red", ls="--", label="Electronic")
plt.plot(data[:, 0], data[:, 2], color="tab:blue", ls="--", label="Nuclear")
plt.annotate("AlN", (1, 20), ha="center", fontsize=20)
plt.annotate("SiC", (3, 20), ha="center", fontsize=20)
plt.xlabel(r"Depth [$\mu$m]", fontsize=16)
plt.ylabel("Energy loss [keV/nm]", fontsize=16)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.xlim(0, 5)
plt.ylim(0, np.max(data[:, 3]) * 1.05)
plt.axvline(2, ls="--", color="tab:grey")
plt.legend(fontsize=14)
plt.tight_layout()
plt.savefig("SRIM_AlN_SiC_maik_zoomed.png")
plt.show()

